### ISSUE TITLE
How to compile the krail-testApp

### ISSUE THREAD

**Issue by cetsupport** [davidsowerby/krail-testApp#7]
Hi,

I'm new to the gradle. But I couldn't find any tasks been define for build.
Any detail instruction about how to build the krail-testApp and test it?

Thanks.

**Comment by davidsowerby** [comment]
Hi

I'm afraid I don't have any detailed instructions for building the test app.   If you wanted just to look at sample code, [krail-tutorial](https://github.com/davidsowerby/krail-tutorial) may be better, as there is a [tutorial](http://krail.readthedocs.org/en/latest/tutorial01/)  to go with that.

However, if you do want to build the test app, in brief, you would need to clone a number of repos:

- krail-master
- krail
- krail-testApp

include these if you want to run the tests

- krail-testUtil
- q3c-testUtil
- krail-bench (requires Vaadin TestBench)


Once cloned, you will need to change your local krail-master director name to 'master'  (this is because that is all Gradle will recognise as a master project)

Either execute the gradle task 'compileJava' from your IDE or


```cd /your/path/git/master```
```gradle clean compileJava```

**Comment by davidsowerby** [comment]
This is now a lot simpler, as I have separated all the projects.  Do you still need help with this?

**Comment by davidsowerby** [comment]
Although I still have to push the latest version to GitHub - probably tomorrow

**Comment by davidsowerby** [comment]
Closed as out of date
